server:
  port: 8081

#spring:
#  cloud:
#    nacos:
#      discovery:
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        cluster-name: NJ