server:
  port: 8080
spring:
  application:
    name: consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        cluster-name: NJ
        ephemeral: false
#        namespace: 24f183e1-f9e8-49a5-abf3-ca3f04f9765a

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
